# LoadBalancer Service. Will only work on supported cloud platforms (AKS, EKS, GKE, DOK, IBM, LKE etc...)
# Listens externally on 80 and forwards to Pod/container on 8080
apiVersion: v1
kind: Service
metadata:
  name: kibana-load-balancer
  namespace: logging
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5601
  selector:
    app: kibana
