# Simple deployment used to deploy and manage the app in nigelpoulton/ps-web:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  minReadySeconds: 5 # minimum time new pod running to terminate the old one
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # During update never drop below the replicas value (10)
      maxSurge: 1 # max go up tp replicas value (replicas + 1)(11)
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: hello-pod
          image: allanweber/getting-started-k8s:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
